repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-symlinks
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.16.3
      hooks:
        - id: ruff
          types_or: [python, pyi]
          args: [--fix, --select=D100,E,F,W]
        - id: ruff-format
          types_or: [python, pyi]
  -   repo: https://github.com/Anselmoo/repo-release-tools
      rev: v1.15.0
      hooks:
        - id: rrt-branch-name
        - id: rrt-commit-subject
        - id: rrt-changelog
