language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip3
install:
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pip3 install pytest-cov
  - python setup.py install
script:
  - py.test --cov tanabe test # Run the tests and check for test coverage.
  - python -m tanabe # Run small d6-example
