name: Plushing Python Package

on:
  release:
    types:
      - published

jobs:
  PyPi-Package-Release:
    if: github.repository == 'Anselmoo/TanabeSugano'
    name: Publish on PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies via poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Install library
        run: poetry install --no-interaction --only main --all-extras
      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.TWINE_TOKEN }}
          poetry publish --build
        continue-on-error: true
